### ISSUE TITLE
Tracking current reported issues

### ISSUE THREAD

**Issue by biohackerellie** [biohackerellie/FlexRoster#863]
### TODO

- [x] Better views to keep track of students from my class and where they go
- [x] Better availability settings and view
- [x] Not getting emails
- [x] Some transfers not working
- [x] Alphabetize by last name
- [x] Increase default row count
